### ISSUE TITLE
Rsa.c, line 250

### ISSUE THREAD

**Issue by hui6075** [mborisov1/rsa_embedded#1]
uint16_t bufmod[MPI_NUMBER_SIZE]; // Modulo buffer, single size
memcpy(bufmod,m,MPI_NUMBER_SIZE*2);

is this a memory overflow?

**Comment by mborisov1** [comment]
No, because the buffer is allocated as uint16_t (2 bytes for each element), reserving a total of MPI_NUMBER_SIZE*2 bytes. On the other hand, the memcpy function receives the buffer size in bytes, i.e. the same amount as the buffer size. No overflows. This code has been tested extensively and is used in some embedded projects. A major buffer overflow would have most likely caused a crash and be noticed long ago. Don't expect easy bugs here.
